### ISSUE TITLE
osexception not imported, and invalid use of _()

### ISSUE THREAD

**Issue by smathot** [dev-jam/opensesame_plugin_-_parallel_port_trigger#3]
The plugin misses the following import:

~~~ .python
from libopensesame.exceptions import osexception
~~~

Also, that you catch the exception and wrap it into an `osexception` is good, but also masks the source of the problem, especially because the `try ... catch` clause spans multiple lines (which, in principle, is not good practice). What you could do is pass the original exception as a keyword to `osexception`, like so:

~~~ .python
try:
    # do something
    pass
except Exception as e:
   raise osexception(u'Could not access the Parallel Port', exception=e)
~~~

In addition, you shouldn't use the `_()` function wrapper for strings in the runtime functionality. It's a GUI thing that uses Qt, and, in case, you haven't imported it!

Also see this forum post (which brought the issue to my attention):

- http://forum.cogsci.nl/index.php?p=/discussion/1993/

**Comment by dev-jam** [comment]
I agree and changed it!
Have to do some more reading on best practices for handling exceptions. 
Also changed the try.. except.. with the import error.
Could you review this code change?

**Comment by smathot** [comment]
Yes this looks good! (Just by eye, haven't tested.)
